apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-ameya
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-ameya
  template:
    metadata:
      labels:
        app: hello-ameya
    spec:
      containers:
      - name: hello-ameya
        image: nginx:latest
        ports:
        - containerPort: 80